### PR TITLE
This improves documentation

### PR DESCRIPTION
**Pull request by paddor**

### CODE REVIEW

**Comment by digitalextremist** [comment]
Awesome, thanks! Just resolve those `RuboCop` errors and I'll merge this.

**Comment by paddor** [comment]
Uhh sure. Looks like some feature of RuboCop isn't available anymore. What's the preference here?

```
Running RuboCop...
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
(configuration found in /home/travis/build/celluloid/culture/rubocop/style.yml)
RuboCop failed!
```

**Comment by digitalextremist** [comment]
Gotcha, I'll update the rubocop ruleset to take care of that.

**Comment by paddor** [comment]
Thanks. I'm not too familiar with RuboCop myself.

**Comment by digitalextremist** [comment]
@paddor understandable. This is the offending line, fyi:

* https://github.com/celluloid/culture/blob/master/rubocop/style.yml#L29

**Comment by paddor** [comment]
Cool. We did the linkedin thing! :smile: 

So which of the 2 new variants is wanted?

**Comment by digitalextremist** [comment]
Awesome, I just saw. Thanks for that --

My guess would be both... but it seems slightly more involved, since `EnforcedStyleForMultiline` would need to be broken out on its own, and `ConfigurableEnforcedStyle` would be used instead.

I'll come back to this.

**Comment by paddor** [comment]
@digitalextremist Any updates on this?

**Comment by digitalextremist** [comment]
Ah, yes, I fixed this. Merging the remaining changes.

**Pull request merged**
