### PR TITLE
rubocop policies

### PR DESCRIPTION
**Pull request by niamster**

### CODE REVIEW

**Comment by digitalextremist** [comment]
:+1: you have my vote @niamster. This is a very awesome PR in terms of the documentation for future/current gems.

Since this is `celluloid/culture` and the ramifications are global, @tarcieri should agree out loud, even if his agreement is already known.. and visa versa if ever I don't arrive first to a decisive change.

**Comment by niamster** [comment]
Thanks @digitalextremist. Feel free to correct my English in the readme file =)

**Comment by tarcieri** [comment]
On RbNaCl I just broke the rubocop config apart into Style vs Metrics like so:

https://github.com/cryptosphere/rbnacl/blob/rubocop/.rubocop.yml

**Comment by digitalextremist** [comment]
I so saw `SingleSpaceBeforeFirstArg == false` coming :)

**Comment by digitalextremist** [comment]
@tarcieri any `inherit` clause, or just override defaults?

**Comment by tarcieri** [comment]
No real opinion there

**Comment by digitalextremist** [comment]
@niamster are you spelling out `inherit` so people know what the defaults are, or so that they aren't unexpectedly changed, or?

**Comment by niamster** [comment]
My intention was to force celluloid subprojects use culture repo as GIT submodule and avoid doing copy-paste. Also it makes clean distinction between the default celluloid best practices and project preferences.

**Comment by digitalextremist** [comment]
I'm merging this to start testing it on `0.17.0`.
Nice work @niamster!

**Comment by niamster** [comment]
@digitalextremist thanks

**Comment by digitalextremist** [comment]
@niamster, FYI: this is happening for submodules of `celluloid/culture` and I'm working to resolve it:

https://travis-ci.org/celluloid/celluloid-supervision/jobs/60330396

```
$ git submodule update
Cloning into 'culture'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:celluloid/culture.git' into submodule path 'culture' failed
The command "eval git submodule update" failed. Retrying, 2 of 3.
```

**Comment by digitalextremist** [comment]
Wait, that needs to be the `http` version vs. the `ssh` version of the repo address.

**Comment by digitalextremist** [comment]
I will update the doc and the submodule

**Comment by niamster** [comment]
Argh, I haven't yet tried with CI. Thanks for the correction.

**Comment by digitalextremist** [comment]
I've got it all fixed and I've gotten #6 fixed, but I'm handling #8 and will be right back

**Pull request merged**
