### PR TITLE
gems: a helper to list x-celluloid dependencies

### PR DESCRIPTION
**Pull request by niamster**
helper script to address #10

### CODE REVIEW

**Comment by niamster** [comment]
Live example in celluloid/celluloid-essentials#11

**Comment by niamster** [comment]
cc @digitalextremist

**Comment by digitalextremist** [comment]
Very nice work @niamster, I woke up to this from you. I see a few light changes but other than that, I'm very happy you did this. Thank you!

By the way, in the future can you branch off of `celluloid/culture` so I can collaborate with you on changes before we pull into master? You're part of the Celluloid :)

**Comment by niamster** [comment]
@digitalextremist I'm glad it was what you've expected

**Comment by digitalextremist** [comment]
You're a ninja @niamster. About done adapting

**Comment by niamster** [comment]
The only thing is bothering me with the GIT submodules is that those are bound by hash. Each time you update culture repo you have to walk through all other repos and update submodules.
I'll think how to automate this.

**Comment by digitalextremist** [comment]
Yes, I'm thinking about this too. I think we need in general to solve #2

**Pull request merged**
